config:
  security.secureboot: "false"
  user.network-config: |
    version: 2
    ethernets:
      eth0:
        dhcp4: no
        dhcp6: no
        optional: true
        addresses: [192.168.2.100/24]
        gateway4: 192.168.2.254
        nameservers:
          addresses: [192.168.2.254]
  user.user-data: |
    #cloud-config
    hostname: maas01
    fqdn: maas01.maas.bru.int.cleem.de          

    locale: "de_DE.UTF-8"
    timezone: Europe/Berlin
    keyboard: {layout: de, toggle: null, variant: ''}          

    chpasswd: { expire: false }
    ssh_pwauth: false
    password: secret          

    package_update: true
    package_upgrade: true
    packages:
      - openssh-server
      - snapd          

    final_message: "Cloud init is done.!"          

    users:
      - default
      - name: ubuntu
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDmlRbfaE4y7z1DcLi0ViI/qDyulpy5aSyJPyS/dUU0ZvUg5Wq/pK734Kv9T026jUysSPTk9uEFc6ZRjFyBcvAmBKr3pepRE3NIEMVaTf2eJ/E6Ipm7Z1yVDM30u7fNxP6kyup5AMWShYe52HQKZOhpV1+KFuE6RA4GJpt17nmfTF/jXf9qrbHY3CuufvE1wWsFhnQZKH2K2hi4OpytAUjdXJbHgjuzd6gkzKRy3DXS/wddU3rgKS9uja9HKVfuBB3DRixi8Y/hB0Ve3dw8WcFVxGhjE1zZmWJZQ93VBxQUBubMW2j5/I71hhbgE+dZ5jXhqK3ppz1HYW6FIdxt0IyCC/bUoPF9FV4MNtsNosz9lCjZcNVbAv7u+0nNKyL6AykptDekzL/mbuLy16EC7IiX6gm8Dud9VX9sRYflFM7kglVxdaFKcngIjnnumpk9WI8+4GY4ASgszAQk/dzl6JdiEtypHs2cyTzF0y29RTJQcHBiMMt0byJLFE4AutIp7jU= clemens@cknb.local
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        groups: sudo
        shell: /bin/bash          

    ntp:
      servers: ['ptbtime1.ptb.de', 'ptbtime2.ptb.de', 'ptbtime3.ptb.de']          

    write_files:
      - path: /etc/sysctl.d/10-disable-ipv6.conf
        permissions: 0644
        owner: root
        content: |
          net.ipv6.conf.all.disable_ipv6=1
          net.ipv6.conf.default.disable_ipv6=1
          net.ipv6.conf.lo.disable_ipv6=1
      - path: /opt/cleem/seed/init.sh
        permissions: 0755
        owner: root
        content: |
          #!/bin/bash
          echo ===== START: INITCMD =====
          CLOUD_NAME=maas01_bru
          CLOUD_USER=admin
          CLOUD_PASSWORD=admin
          EMAIL=admin@maas.bru.int.cleem.de
          PORT=5240
          IP=$(hostname -I | head -n 1 | xargs)
          URL="http://$IP:$PORT/MAAS"      

          echo "INFO: $CLOUD_NAME - Configuring MaaS $URL"
          /snap/bin/maas init region+rack --maas-url $URL --database-uri maas-test-db:///      

          echo "INFO: $CLOUD_NAME - Configuring User $CLOUD_USER $EMAIL"
          /snap/bin/maas createadmin --username $CLOUD_USER --password $CLOUD_PASSWORD --email $EMAIL --ssh-import ''      

          echo "INFO: $CLOUD_NAME - Getting API Key for $CLOUD_USER"      

          API_KEY=$(/snap/bin/maas apikey --username $CLOUD_USER)
          CONFIG_FILE="/opt/cleem/seed/juju-$CLOUD_NAME-cloud.yaml"
          CREDENTIAL_FILE="/opt/cleem/seed/juju-$CLOUD_NAME-creds.yaml"        

          echo "INFO: $CLOUD_NAME - Creating juju cloud config $CONFIG_FILE"        

          tee "$CONFIG_FILE" > /dev/null << END1
          clouds:
            $CLOUD_NAME:
              type: maas
              auth-types: [oauth1]
              endpoint: $URL
          END1      

          echo "INFO: $CLOUD_NAME - Creating juju cloud credentials $CREDENTIAL_FILE"        

          tee "$CREDENTIAL_FILE" > /dev/null << END2
          credentials:
            $CLOUD_NAME:
              anyuser:
                auth-type: oauth1
                maas-oauth: $API_KEY
          END2      

          echo "INFO: $CLOUD_NAME - Adding juju cloud config"
          /snap/bin/juju add-cloud --client -f $CONFIG_FILE $CLOUD_NAME        

          echo "INFO: $CLOUD_NAME - Adding juju cloud credentials"
          /snap/bin/juju add-credential --client -f $CREDENTIAL_FILE $CLOUD_NAME      

          echo "INFO: $CLOUD_NAME - Removing firstboot.service"
          rm /etc/systemd/system/firstboot.service
          #rm -r /opt/cleem/seed
          echo ===== END: INITCMD =====
          reboot      

      - path: /etc/systemd/system/firstboot.service
        permissions: 0644
        owner: root
        content: |
          [Unit]
          Description=One time boot script
          [Service]
          Type=simple
          ExecStart=/opt/cleem/seed/init.sh
          [Install]
          WantedBy=multi-user.target 
    bootcmd:
      - [ sh, -xc, "echo ===== START: BOOTCMD =====" ]
      - [ mkdir, -p, /mnt/usb01 ]
      - [ mkdir, -p, /opt/cleem/seed ]
      - [ sh, -xc, "echo ===== END: BOOTCMD =====" ]    
      
    runcmd:
      - [ sh, -xc, "echo ===== START: RUNCMD =====" ]
      - [ /usr/bin/snap, install, maas ]
      - [ /usr/bin/snap, install, maas-test-db]
      - [ /usr/bin/snap, install, juju, --classic ]
      - [ systemctl, daemon-reload ]
      - [ systemctl, enable, firstboot.service ]
      - [ sh, -xc, "echo ===== END: RUNCMD =====" ]      

    power_state:
      mode: reboot          

description: maas01_bru LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: local
    type: disk
name: maas01
used_by: [] 